### ISSUE TITLE
alphabetize attribute names

### ISSUE THREAD

**Issue by terraswat** [ucscHexmap/hexagram#13]
This should be done in create_colormaps.py so the sorting happens before codes are assigned to categories. This will propagate the sort to the client UI.

Use the default sort except use a case-insensitive sort.

**Comment by terraswat** [comment]
How do we handle new categories added to an existing colormap?

**Comment by terraswat** [comment]
Let the caller set the order with a custom colormap for now. When default colormaps move to the client, how does the caller specify order?

**Comment by mrJeppard** [comment]
default is now to order the legend alphabetically
