### ISSUE TITLE
a union of attributes first lit up 3 nodes, and later lit up 4 nodes

### ISSUE THREAD

**Issue by terraswat** [ucscHexmap/hexagram#15]
A union of two attributes first lit up 3 nodes, and later lit up 4 nodes.

To reproduce:
- use CKCC/v1_nbl on production
- select KRAS and NRAS mutations
- do a union
- sometimes 3 nodes are lit up, sometimes 4

**Comment by mrJeppard** [comment]
No longer reproducible (after repeating 6 times).
