### ISSUE TITLE
download node IDs: select a new list, node IDs do not update

### ISSUE THREAD

**Issue by terraswat** [ucscHexmap/hexagram#16]
When downloading node IDs, the second time you select an attribute, the list of nodes does not update and contains the nodes from the first attribute selected.

Steps to reproduce:
- be sure there are two selectable attributes
- open the download-by-node-IDs window
- select an attribute and node IDs appear in the window, that's good
- close the download-by-node-IDs window
- open the download-by-node-IDs window again
- select another attribute and the previous list node IDs stay in the window

**Comment by mrJeppard** [comment]
recently modified code to be able download any attribute in the shortlist, and can no longer recreate the error.
