### ISSUE TITLE
createMap web API: layout input format detection/validation

### ISSUE THREAD

**Issue by terraswat** [ucscHexmap/hexagram#25]
We should auto-detect the layout input format to reduce errors by the user selecting the wrong format.
Also validate the format of attributes input.

**Comment by terraswat** [comment]
In the spirit of "be liberal in what you accept and strict in what you return" for user interfaces, this is suggested logic to validate layout input files and auto-detect the format:
- if there are 3 columns we assume either an xyPositions file or topSimilarity
    - ignore the first line if it is a header, whether it has a hash symbol at the beginning or not
    - if all of the 1st and 2nd column values are numeric, assume this is an xyPositions file and we're done
    - otherwise assume this is a topSimilarity file
            - verify all of the 3rd column values are numeric and we're done
- if there are more than 3 columns we assume this is clustering data or a full simliarity matrix
    - change NAs to zeroes (does this work for fullSimilarity?)
    - verify all values are numeric except the 1st column and 1st row
    - if row 1 has the same values as column 1 we assume this is a full similarity file and we're done
    - otherwise assume clustering data and we're done
- every error should contain the offending line of data with the format assumption and the reason it failed the validation

**Comment by mrJeppard** [comment]
This is now being used on the production's createMapUI. Logic can be found on the calc server's calc directory in formatCheck.py
