### ISSUE TITLE
add Yulia's cancer classifications

### ISSUE THREAD

**Issue by ucscHexmap** [ucscHexmap/hexagram#34]
classifications: https://training.seer.cancer.gov/disease/categories/classification.html
Looks like kidney tumors are carcinomas, which originate in epithelial cells. 

If you are interested, I annotated all of the TCGA tumors by those classifications for something I needed to do

[annotations.tcga.v2.txt](https://github.com/ucscHexmap/hexagram/files/1213127/annotations.tcga.v2.txt)

**Comment by ucscHexmap** [comment]
classifications: https://training.seer.cancer.gov/disease/categories/classification.html
Looks like kidney tumors are carcinomas, which originate in epithelial cells. 

If you are interested, I annotated all of the TCGA tumors by those classifications for something I needed to do

**Comment by terraswat** [comment]
If anyone wants this they may add it.
