### ISSUE TITLE
cholangiocarcinoma, mesothelioma, testicular per Yulia

### ISSUE THREAD

**Issue by ucscHexmap** [ucscHexmap/hexagram#37]
about putting up cholangiocarcinoma map. That paper published back in January. Maybe by that time mesothelioma and testicular papers will be out too.

**Comment by mrJeppard** [comment]
Where is the data for this?

**Comment by ucscHexmap** [comment]
Sorry, forgot to include the data.
"The cholangio paper has been published in Cell Reports (http://www.cell.com/cell-reports/abstract/S2211-1247(17)30214-0)." per Yulia.

**Comment by mrJeppard** [comment]
mmmmn, I don't see a raw data file linked in the paper... also would take a good amount of work on our part to make a tumor map out of this. Probably best for her to use the create map UI and we can make them public for her.

**Comment by terraswat** [comment]
If anyone wants this they may create a map.
