### ISSUE TITLE
context menus: shortlist and shortlist entry

### ISSUE THREAD

**Issue by ucscHexmap** [ucscHexmap/hexagram#40]
Add a menu to each attribute in the shortlist. Candidates:
* reflections
* stats
* set operation
* download
* edit colormap
* create attribute from filter
* create attribute from thresholds

A shortlist global menu could have:
* add attribute function
* remove all entries
* always move active entries to the top of the list (a toggle)

![mini_menu](https://user-images.githubusercontent.com/13859681/29388449-a43883ae-8299-11e7-9bbe-026fa814133b.png)

**Comment by terraswat** [comment]
implemented
