### ISSUE TITLE
ability for user to see a list of sample IDs in xena

### ISSUE THREAD

**Issue by ucscHexmap** [ucscHexmap/hexagram#42]
Currently a user can copy a list of node IDs, then paste them into xena by clicking on the 'custom xxx' button.

Instead of the manual copy and paste method, there could be a button on the tumor map that would bring up xena in a new tab with those samples already added.

The result would look like this:
https://xenabrowser.net/heatmap/?bookmark=854debaea99c61494f190e108dd95d33

**Comment by terraswat** [comment]
no use case
