### ISSUE TITLE
UI improvement for changing attribute color mapping

### ISSUE THREAD

**Issue by chkw** [ucscHexmap/hexagram#50]
We are constantly being asked to change attribute colors. We need an easier way to do it.

1) Changing the color mapping for an attribute should be a button available on the attribute from the short list.

2) A colormap should appear where the actual colors can be selected, possibly from a color wheel. It is way too cumbersome the way its implemented now.

**Comment by terraswat** [comment]
Requested again at presentation 2/28/2018.

**Comment by terraswat** [comment]
This will go in with the context menu

**Comment by terraswat** [comment]
implemented
