### ISSUE TITLE
ability to change colors on continuous values

### ISSUE THREAD

**Issue by terraswat** [ucscHexmap/hexagram#53]
Use a colormap entry and allow the user to define two colors for the min and max of the values.

We need to maintain a reasonable display of colors when there is a primary and secondary attr displayed.

**Comment by terraswat** [comment]
related to #32

**Comment by alanasweinstein** [comment]
Just wanted to voice my support for this feature. When showing multiple maps side-by-side (but highlighting a different gene activity feature, for example), it can look strange for the maps to look so similar... ability to choose colors would help this. Thank you

**Comment by terraswat** [comment]
fixed a while ago
