### ISSUE TITLE
^M (return character) in colormaps.tab

### ISSUE THREAD

**Issue by ucscHexmap** [ucscHexmap/hexagram#6]
Sometimes return characters are in the colormaps file. It is coming from the code that generates the file and no interaction with a spreadsheet. They are between the attribute name and tab character and between the category value and tab character.

They show up in vim as ^M, for example:

`Node ID^M       0       TARGET-30-PASMJG-01^M   #0000FF 1       TARGET-30-PARAMT-01^M   #00FF00 2       TARGET-30-PARHAM-02^M^M   #00FFFF 3       TARGET-30-PATAYJ-01^M   #FF0000`

We should be using the built-in python csv library rather than our tsv.py.

**Comment by mrJeppard** [comment]
Believed to be fixed. Since this was reported we have changed the colormaps generation, and input/output functions (now in process_categoricals.py) for colormaps.
