### ISSUE TITLE
map name options

### ISSUE THREAD

**Issue by alanasweinstein** [ucscHexmap/hexagram#62]
Some of my map names are quite long, to the point where I can't see the full name in the "Map:" drop-down menu. Is there a way to see the full name? I can't "scroll" to the right within the menu... perhaps that's an option, or perhaps the full name could display in a mouseover, if there isn't already a way. 

Alternatively and/or additionally, the option to rename a map would be great.

**Comment by terraswat** [comment]
Added a tooltip to map names in the map list
